# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62d6b29bd822165fa65e0dcb0035d32ea43fda028e928803667d42b92dbeddb3faadbba00ce945dbf24a0fe55c33af427d4ea4a48fec940ebefd0091484b358
  google_client_id: 532477076626-amlq02d6r546tv6ojkluvu959c8ifdos.apps.googleusercontent.com
  google_client_secret: iuz74_NI-xijQbSBYIVjlpDa
  mail_sender_pw: jessica.94


test:
  secret_key_base: 0e1cec6302ce34c6bf8109acfcd7baa0af24c17a3d22c0b58306ea6c5a0e8c951d803dac8d275fc53ab1b598a917f87496c1a8582e2ca6195cfbf08e68dfce40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
